import type { Metadata } from "next";
import { VT323 } from "next/font/google";
import "./globals.css";

const vt323 = VT323({
  weight: "400",
  variable: "--font-vt323",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("lol",vt323.variable)
  return (
    <html className="h-full" lang="en">
      <body
        className={`${vt323.variable} antialiased h-full`}
      >
        {children}
      </body>
    </html>
  );
}
